env:
  global:
    - secure: gbAtpahbElbW7KNQzDd3WY5wlrx5IZ8+pY9g/Ec6p4vbdCrgFMfyISj6uDJJjtsUFIAoad/F6NmwcFfTxPKhvxg39oWJ0tKAvdChfpEzwGEQJHcWqTkB8dExKtUjC83dbMSpcRzklySM1escHS+Q+JShXqDVfpDjrHbvBc8l5hGII/KJ+gKBmeuixA+K8Xu533jl00qiHIGUS5lpHuX2DPDEX0OrXyF9fW79UScHpT6+qZuRVzCTbeGSVH+R7QBCNUW0oAqpvUMJiHd5ra7M7GCs0ABwFl9AAW7n60wcz+/bmJ4spGeOSLjPVGH4NHHJ2f4D5+cVSwMV4Xbitmj7WHRGCNr/2p6r3KSoD9aUf5Wkz6YFU59DVNEnsUnMMDGv6rNfRywQiAv+K+LYfevv8EGFgfPBoeV1PRlc4PNniSntzvK3GAEkKDCAzgYKL3xOFhe7YovAUOaVf/tEVYjm2rC4Sexpt+FXVjByDXmBDHZSHwrKyQGwFaXsDIPKV+/B+ux/lcr7NEWxl8XoAh06UhAcniJyMHtzrN84ATTs5o0B1OELqX7SSLjZX0uo2/Fs17e7vzBml63BjqN3XqscKs2qG1Sj9bGxSgwe+zwlbEChV5TNiqvroj4VQPTJq5Uau8SmAVsHkUpiDWmYe+yuEzxJBZwHc5uvDzdtgT02/mc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Bad_JAV_Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
