env:
  global:
    - secure: bvZ8C1srs4pqb0iYXQbc4caF4IO47K/LpFUI6FxUNutwwdXpwzS3ERlMtTUbfYAe/itywtE03/bV9m4g+FJG9hV1QM1XUWbaM6+RNqq6TTRa53pTimS39hraGP+5kjKZDQbI6MjGixKHKXh4i/LZutFU1NNvc9CQ+xRR+vQj8xpKecPErojygG+Ghcyhf2mJgEGrrGuvS8qXuGuBkxMdyOFhYEuWV9pQJ3IyjiMvzWKfrfUyF+AGU/maCQxmVS4Cwf6dbAv9b6qbvf5VmCwgYw4FIsG120lPKX9cXsVD2/EkQgNbaWuktFcIQP2fQ8g5iUgBPb33RVppr+6lIhD9BeEOSU1AyH1DEtMdQEmIb7HdTHgje/k1RpLqIA7DqRCa0O8bTQ6MHSUmpcIcmdm+ynZb1waoDQ5+p6HAkNmdR3r2HFvVG8oxaoySqzHEm+vR8nADcZ8lu7K+fnDBG8o11Mdp8Sb3eADd/E2MCTG6vj7fodiUF+zNUvwqcQ0o3te2hOClLGBtxnyuquU2iJAHhxzcGB6VMO4gJuyAl5fBg/hmqkYjC2foP2q9SjHpIfRhRacguwHRe97dODeb9gnpBAvCE2KxsdVj4mfijxC/+e35czVGvFkd4ndSxK0VkwlEaw9qwzX7mWA5v222o8i45mBwvZCrqxhSD5i9fR7bC8E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Bad_JAV_Sites
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
