env:
  global:
    - secure: mAc812a9racvnxTWRMAfVurvrcybcV9L8pvzC8M4ulRxu8hepVImCWYAoa+qixUs02k3H4fFJGnojiS3cBKE9GpIzEBW5r471+uJnC3FbRb5tQq5Cjof2+FbexHBHqhJ6DX09CBIKL5xXof74GDkgF5WfMCMlBWK8sfHoGigocjFez1Ukv7QFHLsaoHSCaIzCXoY8HdbkzNV7U9LfGE+qiifMmDu8WgtLOsguu36QNG8ttXFbXB3pe5cTt66yIdey13Vvkx4YxkcTeVHxzwxsRWWxHy99l4O4lmOi/NQISFHbKoXWWdK6R8e4tQvSEx5hlmCYHjHGcvgvQC50+zVJoxMEEJMe5A++4G8igZzxcHNfOn3WTXWpL8/vf61b/uVBRUUk8yka/MqRPEKgtV1+S/oFTaayX+SFpJEGqDc14mZokBv9roj8urowJXNJ3fbgLnQqkWal5HbD5jrC979vzD/B6MEcrfEFXCrfTLKOoBkcn4F6K7I+zyfleUxKf4z03HzBq0Va7TKabZcUcJTd+PY4a+OMNGAoEAijLIDoMzHTEaybEvQQyPp7qeFuegu4urMkA/D7tXsSmKKaPEmm0DBY6hFwTCTos/Qb8sIK+dbNjP/GSPiDrVFC4SXrukja7wxqHJH/GUN+4hGQWwysOq0+3SekfaO3fsdV8fPs8c=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Bad_JAV_Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
