env:
  global:
    - secure: e9Z06RbeU0Yo9U7tzCJRv4FhXURtP6XVdf6zexvnWDyZ1O1pK2UXphInv1xJlTbt5B/T2indQ1vIOpzz4J5aApr+/wYrnjSob9sxtQK34IL5ssy6TNiMgOeS6p0EZCiXoJAkx7wZY9SjrTSq8uPXZCI/4ltM03uyG4SjmV5IjBze/EQd1QpK86a+aXSmQQDZ2OHC7xcAZcVIsxDYCWWK30TeaAmcS9ADfXCihMwQefPqK47+GG4w5rfdTHk2Qd/S0f0V8qgTGNUEizM/FhZ5f+LiOycs1dH62sc0c6KK5CX7oi0OzPtMjZ7oYB9brOYBMOsSMICCcY7o6G3CR5g4/g/KZvMRc4wBp6ZhdOrBCAY0RUC/dZOA/FABpCjw7B6woFhXO+NwDiURXrcukBCqB1SAJ8fYeU7VjafT/OFwa+ayJEoeSHyCWniM8YkwpTc9+kyW5Xuwpz5WIJ3/IGcHis67brFcWMsrMaYldAn60iYLhI5XkoK6lvTzUORbDAtL3KsjyXPM6v8wlryvxeDsx8Xy0wLe6NpSM76QQlR1cjjo42VEMl4hB8j8uGc1FoqdiRjSYc3fCz3Ogz5RNuBaa4ddm7FLUKVdAN7428cfsBkrK+JA2Y9VE1QbP1As6reTYmF8XzrnMFOSf8ssT//Gke3Af7vQB2mPEVhWeFhUdGM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Bad_JAV_Sites
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
